{% set name = "azure-identity" %}
{% set version = "1.17.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32ecc67cc73f4bd0595e4f64b1ca65cd05186f4fe6f98ed2ae9f1aa32646efea

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - typing-extensions >=4.0.0
    - azure-core >=1.23.0
    - cryptography >=2.5
    - msal >=1.24.0
    - msal_extensions >=0.3.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - azure.identity
    - azure.identity._credentials
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity
  summary: Microsoft Azure Identity Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelotrevisani
    - dhirschfeld
