{% set name = "azure-identity" %}
{% set version = "1.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 500144dc18197d7019b81501165d4fa92225f03778f17d7ca8a2a180129a9c83

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - typing_extensions >=4.0.0
    - typing-extensions >=4.0.0
    - azure-core >=1.31.0
    - cryptography >=2.5
    - msal >=1.30.0
    - msal_extensions >=1.2.0
    - python >=3.7

test:
  imports:
    - azure.identity
    - azure.identity._credentials
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity
  summary: Microsoft Azure Identity Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelotrevisani
    - dhirschfeld
