{% set name = "azure-identity" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/azure_identity-{{ version }}.tar.gz
  sha256: 40597210d56c83e15031b0fe2ea3b26420189e1e7f3e20bdbb292315da1ba014

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - azure-core >=1.31.0
    - cryptography >=2.5
    - msal >=1.30.0
    - msal_extensions >=1.2.0
    - typing_extensions >=4.0.0

test:
  imports:
    - azure.identity
    - azure.identity._credentials
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity
  summary: Microsoft Azure Identity Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
    - dhirschfeld
